version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 66206620
      MYSQL_DATABASE: talkaway
      MYSQL_USER: talkaway_admin
      MYSQL_PASSWORD: talkaway@2024
    restart: always

  web:
    build: .
    volumes:
      - logs:/var/www/django/log/talkaway
      - ./static:/var/www/django/talkaway/collected_static
    ports:
      - "8068:8068"
    depends_on:
      - db


  nginx:
    container_name: nginx-container
    build: ./nginx
    restart: always
    volumes:
      - ./log:/var/log/nginx
      # 專案的的下一層會建立static 對應到 docker內的 colleted_static
      - ./static:/var/www/django/talkaway/collected_static
    ports:
      - "80:80"       
    depends_on:
      - web

volumes:
  db_data:
  logs:
  static: