# Generated by Django 5.0.1 on 2024-06-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioninteractions',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='thirdpartylogin',
            options={'verbose_name': '時間戳記', 'verbose_name_plural': '時間戳記'},
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(max_length=50, unique=True, verbose_name='會話ID')),
            ],
            options={
                'verbose_name': 'GPT會話',
                'verbose_name_plural': 'GPT會話',
                'indexes': [models.Index(fields=['chat_id'], name='gpt_chat_chat_id_9f5577_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', '系統設定'), ('user', '使用者輸入'), ('assistant', '系統回應')], max_length=50, verbose_name='角色')),
                ('content', models.TextField(verbose_name='內容')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='gpt.chat', verbose_name='GPT會話')),
            ],
            options={
                'verbose_name': '對話互動歷史紀錄',
                'verbose_name_plural': '對話互動歷史紀錄',
            },
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='SessionInteractions',
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['created_at'], name='gpt_chathis_created_3e3045_idx'),
        ),
    ]
